import boto3
import os
from sagemaker.pytorch import PyTorch

# Set dummy env vars to avoid boto3 errors if it tries to fetch region
os.environ["AWS_DEFAULT_REGION"] = "us-east-1"
os.environ["AWS_PROFILE"] = "tutor-deploy"

# We just want to see the dictionary generated by the PyTorch Estimator
estimator = PyTorch(
    entry_point="train_genrec.py",
    source_dir=".",
    role="arn:aws:iam::111122223333:role/dummy",
    instance_count=1,
    instance_type="ml.g4dn.xlarge",
    framework_version="2.0.1",
    py_version="py310",
    sagemaker_session=None,
)

job_name = "test-job"
# We can't easily print the payload without monkey-patching create_training_job,
# but we can look at the estimator.hyperparameters()
print(estimator.hyperparameters())
